version: '3.9'

services:
  db:
    image: mongo:6.0-rc-jammy
    ports:
      - 27017:27017
    env_file: .env
  api:
    build: .
    ports:
      - 8080:5000
    env_file: .env
    depends_on:
      - db
